-- File: SV_SERVICEM_T.sql
-- Oracle 11g - Create table SV_SERVICEM_T

CREATE TABLE SV_SERVICEM_T
(
    SSMT_JOB_NO      VARCHAR2(10),
    SSMT_TYPE_CODE   VARCHAR2(1),
    SSMT_TYPE_SEQ    NUMBER(2),
    SSMT_ENDJOB_DATE DATE,
    SSMT_STATUS      VARCHAR2(1),
    SSMT_DATE_ST     DATE,
    SSMT_DATE_ED     DATE,
    SSMT_EMPCODE     VARCHAR2(6),
    SSMT_USER_ID     VARCHAR2(20),
    SSMT_USER_DATE   DATE
);

-- ===== Column Comments =====
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_JOB_NO      IS 'รหัสแจ้งรับงาน ดูตาราง BK_TARM_T';
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_TYPE_CODE   IS 'รหัสประเภทงานให้บริการ ดูตาราง SV_SERVICE_TYPE_R';
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_TYPE_SEQ    IS 'เลขลำดับงาน';
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_ENDJOB_DATE IS 'วันที่กำหนดแล้วเสร็จ';
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_STATUS      IS 'สถานะการดำเนินการ ดูตาราง SV_STATUS_R';
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_DATE_ST     IS 'วันเวลาเริ่มดำเนินการ';
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_DATE_ED     IS 'วันเวลาที่ดำเนินการแล้วเสร็จ';
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_EMPCODE     IS 'รหัสพนักงานที่ดำเนินการ';
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_USER_ID     IS 'รหัสเครื่องที่ใช้งาน';
COMMENT ON COLUMN SV_SERVICEM_T.SSMT_USER_DATE   IS 'วันเวลาที่ใช้งาน';
